# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb013b6b714b23e1ccb194e8683f3bef8a95eb2108d8c134e71b460c5cb395ef99bdb0e43b68e197e89922aada009e51ad09a5862feae6bb1e62de1e26f48ca7

test:
  secret_key_base: 122b803b6d328e2c69f67eb3060f0012bf7be041021a1b5fe1e0d23605ab83c52cadddfb811b98544aec2870360c179e94c8870988fd0c92be9304ec9eb778ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
